source ~/.zshenv
source ~/.zsh/config
source ~/.profile

# use .localrc for settings specific to one system
[[ -f ~/.localrc ]] && . ~/.localrc

export PATH="$PATH:/usr/local/share/npm/bin:/usr/local/oracle:/usr/local/heroku/bin"
export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting
export PATH="/usr/local/opt/postgresql@9.5/bin:$PATH"

#### BEGIN GENERATED BY install-rbenv.sh ####
export PATH=/Users/joealba/.rbenv/bin:${PATH}
eval "$(rbenv init -)"
#### END GENERATED BY install-rbenv.sh ####

#### BEGIN GENERATED BY HANDYDEV TOOLKIT ####
alias 'shopt=:'
autoload bashcompinit
bashcompinit
source /Users/joealba/dev/mojotech/handy/meta/init.sh
#### END GENERATED BY HANDYDEV TOOLKIT ####

export AWS_PROFILE=handy

eval "$(pyenv init -)"
